@apiUrl = http://127.0.0.1:8080/rooms

### Get all products
GET {{apiUrl}}

### Get one product

GET {{apiUrl}}/1002

### Create new product 

POST {{apiUrl}}
Content-Type: application/json

{
    "name": "Jeans",
    "price": 75
}

### Delete product 

DELETE {{apiUrl}}/1005

### Update product

PATCH {{apiUrl}}/1001
Content-Type: application/json

{
    "price": 75
}


